### ISSUE TITLE
[Task] post, product, reservation API

### ISSUE THREAD

**Issue by YeChan8812** [codestates/Campbu#106]
### ISSUE
- Group: server
- Type: feature
- Detail: post, product, reservation API 토큰 연결, posts 정보 내려줄 때 likes_count 및 reviews 정보 포함 

### TODO
 1. [ ] 각 API token 함수 연결
 2. [ ] token에 담겨있는 유저 정보로 유저 fk 넣기
 3. [ ] posts에 likes_count 정보 포함시켜서 보내기
 4. [ ] posts에 reviews 정보 포함시켜서 보내기

### Estimated time `3h`
