### ISSUE TITLE
[Task] 상세페이지 페이지 뼈대 구성

### ISSUE THREAD

**Issue by bgyoons** [codestates/Campbu#11]
### ISSUE
- Group: client
- Type: feature
- Detail: 상세페이지 페이지 뼈대 구성

### TODO
 1. [x] 찜하기 컴포넌트 생성
 2. [x] 리뷰 컴포넌트 생성
 4. [x] 상세페이지 뼈대 빼치 
### Estimated time
`3h`
