### ISSUE TITLE
[Task] 목록 페이지 페이지 뼈대 구성

### ISSUE THREAD

**Issue by bgyoons** [codestates/Campbu#12]
### ISSUE
- Group: client
- Type: feature
- Detail: 목록 페이지(찜, 대여, .. 총 4개) 페이지 뼈대 구성

### TODO
 1. [ ] 상품 컴포넌트 만들기
 2. [ ] 빌려준 목록, 빌린 목록
 3. [ ] 찜한 목록, 내가 쓴 글
 4. [ ] 비어있는 페이지

### Estimated time
`3h`
