### ISSUE TITLE
[Task] 메인페이지 기능구현

### ISSUE THREAD

**Issue by hinyc** [codestates/Campbu#121]
### ISSUE
- Group: client
- Type: feature

### TODO
 1. [x] 바뀐 api 문서대로 데이터 수정
 2. [x] 상태 오타 수정
 2. [x] 카테고리 이미지 추가(피그마, 코드 적용)
 2. [x] 카테고리별 분류
 4. [x] 주소 검색, 카테고리 분류 따라 상태 관리(원본 지키기)

### Estimated time
`3h`
