### ISSUE TITLE
[Task] 메인페이지 기능구현 - 찜하기

### ISSUE THREAD

**Issue by bgyoons** [codestates/Campbu#134]
### ISSUE
- Group: client
- Type: feature

### TODO
 1. [x] 찜하기 버튼 클릭 시 `POST`
 2. [x] 찜하기 버튼 클릭 시 로그인 상태가 아닐 경우 로그인 모달 활성화
 3. [x] 찜한 상태에 따라 찜 채우고 숫자 바꾸기

### Estimated time
`3h`
