### ISSUE TITLE
[Task] 소개 페이지 뼈대 구성

### ISSUE THREAD

**Issue by bgyoons** [codestates/Campbu#15]
### ISSUE
- Group: client
- Type: feature
- Detail: 소개 페이지 페이지 뼈대 구성

### TODO
 1. [x] Index에 폰트 적용(Noto Sans KR)
 2. [x] 네비바 컴포넌트 뼈대 만들기
 2. [x] 푸터 컴포넌트 뼈대 만들기
 2. [x] 소개 페이지 소개 문구, 인풋, 검색 버튼

### Estimated time
`3h`
