### ISSUE TITLE
[Task] 대여 목록 예약 관리

### ISSUE THREAD

**Issue by bgyoons** [codestates/Campbu#158]
### ISSUE
- Group: client
- Type: feature

### TODO
 1. [x] 상품 예약 상태 관리
 2. [x] 예약 후 예/아니오 모달 상태 관리
 3. [x] 리뷰 모달 띄우기
 4. [x] 선택한 리뷰 아이디 모으기
 5. [x] 리뷰 목록 수정
 3. [x] 예약 버튼 `DELETE`, `PATCH` 코드 작성
 4. [x] API 문서 따라 상태 변수 바꾸기

### Estimated time
`3h`
