### ISSUE TITLE
[Task] 회원가입 기능구현

### ISSUE THREAD

**Issue by bgyoons** [codestates/Campbu#18]
### ISSUE
- Group: client
- Type: feature

### TODO
 1. [x] 이메일 형식 검사
 2. [x] 이메일 중복 검사(API)
 2. [x] 비밀번호 유효성 검사(영문, 숫자 8자리 이상)
 3. [x] 비밀번호 일치 검사
 4. [x] 닉네임, 이메일, 비밀번호 API 연결(로컬 서버)
 5. [x] 약관(더미) 만들기
 6. [x] 회원가입 버튼 조건에 따라 활성화

### Estimated time
`3h`
