### ISSUE TITLE
[Task] 세부적인 기능 수정 (계속 추가)

### ISSUE THREAD

**Issue by bgyoons** [codestates/Campbu#208]
### ISSUE
- Group: client
- Type: bug, feature, style

### TODO
1. [x] @hinyc 파비콘 수정
1. [x] @hinyc 이미지 드래그 불가 추가 (구글,카카오로그인아이콘, 검색돋보기 이미지, 상세페이지 제품이미지, 글쓴사람 프로필이미지)
1. [x] @hinyc 계정정보 수정후 업데이트된 계정정보로 갱신
1. [x] @hinyc 내가올린물건 예약이 가능함 --> 불가능하게 수정
1. [x] @hinyc 기본프로필이미지 설정 (Navbar, Mypage, MainDetail)
1. [x] @hinyc 대여료 일 수 아닌  박수 기준으로 계산
1. [x] @hinyc 선택된카테고리에서  검색시 전체 물품 검색되는버그
4. [x] @bgyoons 대여 목록 페이지 빈 페이지 띄우기
2. [x] @bgyoons 메시지함 사진 받아오기
2. [x] @hinyc 찜하기 클릭후 해당 상세페이지 들어가면 빈하트가 표시됨 새로고침시 꽉찬 하트로나옴
3. [x] @bgyoons 마이페이지 네비바 너비 넓히기, 목록을로 돌아가기 추가
1. [x] @hinyc 선택된 카테고리 표시
1. [x] @hinyc 글쓰기 버튼 포인터추가
1. [x] @hinyc 모든 이미지나 그림에 draggable='false'설정
11. [x] @hinyc  물건 예약시 예약날짜 대여불가 날짜에 추가필요
 22. [x] @bgyoons 목록 페이지에 더미데이터 노출되는 부분 해결
 23. [x] @bgyoons 로그인 후 드롭다운 켜져있는 버그
 23. [x]  @bgyoons 메시지, 로그인, 회원가입 모달 정렬/스타일
 1. [x] @hinyc 상세페이지 리뷰 클릭 안되게 수정
19. [x] @hinyc  인트로 페이지 네브바 너비 지정
 1. [x] @hinyc 로그아웃후 직전 로그인아이디의 찜하기 상태가 유지되는 버그 해결
20. [x] @bgyoons 예약 취소(삭제) 시 메시지 목록에서 삭제(서버 깨짐)
21. [x] @bgyoons 메시지함 목록에서 방 선택 안한 경우 인풋창 숨기기(서버 깨짐)
22. [x] @bgyoons 메시지함 선택, 비어있는 경우 페이지 추가
 18. [x] @hinyc 메인페이지 찜하기 값불러오기 수정
 2. [x] @hinyc 로그인 성공 후 원래 있던 페이지에 머무르기
 12. [x] @bgyoons 예약 완료시 완료 확인창 모달
 5. [x] @bgyoons 엔터 시 버튼 동작(검색, 로그인)
 6. [x] @bgyoons 예약 상태 업데이트 시 버튼 색 변경 -> 소켓 / 새로고침 / 강제 리렌더 등
 7. [x] @bgyoons @hinyc 상세 페이지 들어갈 때 초기값 0인 부분 해결하기(서버 터짐) 
 8. [x] @bgyoons 메인페이지 상품 목록에 이미지 썸네일 해결(string 값으로 되어 있음 -> string[]으로 고치기)
 11. [x] @bgyoons `key prop warning` 해결
 9. [x] @bgyoons 로딩 컴포넌트 애니메이션
 12. [x] @hinyc 내가쓴글이 없을때 글쓰러가기 메시지에 링크 추가 
 12. [x] @hinyc 유저정보및 선택된 포스트아이디 로컬스토리지 관리
 4. [x] @bgyoons 전반적으로 폰트, 박스 사이즈 키우기
 15. [x] @bgyoons 검색해주세요 페이지
 16. [x] @hinyc 예약 날짜 선택시 대여일, 반납일 선택상태에서 대여일 재선택시 대여불가인날도 포함될수 있는 버그 수정
  3. [x] @hinyc 주소 검색 후 주소 클릭시 바로 결과페이지로 이동
  4. [x] @hinyc 메인페이지나, 내글목록에서 바로 사라지게 하기(지금은 새로고침후 사라짐)
 13. [x] @hinyc  메인페이지 포스트 이미지 드래그 안되게 수정
  15. [x] @hinyc 푸터 아래에 붙이기
 16. [x] @hinyc 예약하기기 대여 반납선택해야 예약가능하게 하기, 예약하기 누를시 달력 안보이게하기
 1. [x] @hinyc 드롭다운 다른 영역 클릭하면 사라지기
 14. [x] @hinyc 메인페이지 포스트 커서 스타일 추가
 12. [x] @bgyoons 메시지랑 대여 상태 연결
 10. [x]  @bgyoons 푸더 링크 기존 글씨색 수정
17. [x] @hinyc 리스트들 상태변화시 업데이트하기 및 빈페이지 물건보러가기 메인페이지로 링크
 

### Estimated time
`3h`
