### ISSUE TITLE
[Task] 부재 중에 온 채팅 개수 표시

### ISSUE THREAD

**Issue by YeChan8812** [codestates/Campbu#211]
### ISSUE
- Group: server
- Type: feature
- Detail: 전역 변수를 사용하여 부재 중일 때(로그아웃했을 때, 채팅 페이지 외 다른 페이지에 있을 때, 다른 사람과 채팅 중일 때) 온 채팅 숫자 표시

### TODO
 1. [ ] 채팅 개수 관리 전역 변수 객체로 만들기
 2. [ ] 전역 변수로 만든 객체에 total, 각 룸 번호로 채팅 개수 관리
 3. [ ] 각 채팅 룸에 채팅 온 개수 표시
 4. [ ] 다른 페이지에 있을 때 마이페이지 드롭다운 버튼에 개수 표시

### Estimated time `3h`
