### ISSUE TITLE
[Task] Client 리팩토링 테스크

### ISSUE THREAD

**Issue by bgyoons** [codestates/Campbu#261]
### ISSUE
- Group: client
- Type: bug

### TODO
 1. [ ] 검색 결과 후 렌더링되는 첫 페이지가 '검색결과가 없습니다'로 뜨는 문제(전체보기 카테고리를 클릭해야 결과가 나옴)
 2. [ ] 마이페이지 정보 수정 문제
 3. [ ] 찜하기 버튼 문제
 4. [ ] 로그인된 상태가 아닌데 로그인된 네비바
 5. [ ] 목록 페이지 렌더링 시 비어있는 화면 잠깐 노출됨
