### ISSUE TITLE
[Task] 메인페이지 상태관리

### ISSUE THREAD

**Issue by bgyoons** [codestates/Campbu#30]
### ISSUE
- Group: client
- Type: feature

### TODO
 1. [x] 메인 페이지 상태 관리
 2. [x] 메인페이지에 쓸 posts 더미데이터로 목록 페이지(대여, 찜, 내가 쓴 글) 상태 관리 시도
---
 2. [ ] GET 요청으로 포스트 리스트 받아오기
 2. [ ] 카테고리 필터 기능
 2. [ ] 주소 검색 시 서버측에서 받은 주소에 따라 필터링
 3. [ ] 찜하기 구현(클릭시 하트 채워지고 +1, GET 요청)

### Estimated time
`3h`
