### ISSUE TITLE
[Task] 뼈대 페이지 스타일 추가, 컴포넌트 재사용

### ISSUE THREAD

**Issue by bgyoons** [codestates/Campbu#86]
### ISSUE
- Group: client
- Type: style

### TODO
- [x]  소개페이지 사진 삽입 (+ 스타일)
- [x]  푸터 맨 아래 붙이기 (+ 스타일)
- [x]  네비바 드롭다운 버튼 컴포넌트
- [x]  메인페이지 카테고리, 검색 부분
- [x]  폰트가 먹는지 안 먹는지 확인 >> 나중에

### Estimated time
`3h`
